PlayerDB:
  url: jdbc:mysql://localhost:3306/database
  User: test
  Pass: test
RewardDB:
  url: jdbc:mysql://localhost:3306/database
  User: test1
  Pass: test1
LookupURL: http://www.dummy.com/lookup.php?name=%name%
